server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-account
          uri: http://localhost:8002
          predicate:
            - Path=/ms-account/**
          filters:
            - StripPrefix=1
        - id: ms-operation
          uri: http://localhost:8001
          predicate:
            - Path=/ms-operation/**
          filters:
            - StripPrefix=1