server:
  port: 8001
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.r9lfo.mongodb.net/operation
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: *